/** algsRaw.ts — 由 rubik-cube.html algs.js 提取（勿手改）。
 * 公式名 + 算法串；加载时逐条 applyAlg 验证并分类（pureLL / rouxSafe），
 * 不符其类别的算法被丢弃（只让库变小，绝不让错误序列进入解法）。 */
export const ALG_RAW: Array<[string, string]> = [
    // last layer orientation
    ['Sune', "R U R' U R U2 R'"],
    ['Anti-Sune', "R U2 R' U' R U' R'"],
    ['Sune-L', "L' U' L U' L' U2 L"],
    ['Anti-Sune-L', "L' U2 L U L' U L"],
    ['OLL-H', "R U R' U R U' R' U R U2 R'"],
    ['OLL-Pi', "R U2 R2 U' R2 U' R2 U2 R"],
    ['OLL-T', "r U R' U' r' F R F'"],
    ['OLL-L', "F R' F' r U R U' r'"],
    ['OLL-U', "R2 D R' U2 R D' R' U2 R'"],
    ['OLL-line', "F R U R' U' F'"],
    ['OLL-dot', "f R U R' U' f'"],
    ['OLL-sledge', "R U R' U' R' F R F'"],
    ['OLL-fat', "F R U R' U' R U R' U' F'"],
    ['OLL-6', "r U R' U R U2 r'"],
    ['OLL-7', "r U2 R' U' R U' r'"],
    ['OLL-33', "R U R' U' R' F R F'"],
    ['OLL-44', "f R U R' U' f'"],
    // last layer permutation
    ['T-perm', "R U R' U' R' F R2 U' R' U' R U R' F'"],
    ['Y-perm', "F R U' R' U' R U R' F' R U R' U' R' F R F'"],
    ['Ja-perm', "R' U L' U2 R U' R' U2 R L"],
    ['Jb-perm', "R U R' F' R U R' U' R' F R2 U' R' U'"],
    ['Ua-perm', "R U' R U R U R U' R' U' R2"],
    ['Ub-perm', "R2 U R U R' U' R' U' R' U R'"],
    ['H-perm', "M2 U M2 U2 M2 U M2"],
    ['Z-perm', "M2 U M2 U M' U2 M2 U2 M' U2"],
    ['Aa-perm', "x R' U R' D2 R U' R' D2 R2 x'"],
    ['Ab-perm', "x R2 D2 R U R' D2 R U' R x'"],
    ['Ra-perm', "R U' R' U' R U R D R' U' R D' R' U2 R'"],
    ['Rb-perm', "R2 F R U R U' R' F' R U2 R' U2 R"],
    ['F-perm', "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R"],
    ['Ga-perm', "R2 U R' U R' U' R U' R2 U' D R' U R D'"],
    ['Gb-perm', "R' U' R U D' R2 U R' U R U' R U' R2 D"],
    ['Gc-perm', "R2 U' R U' R U R' U R2 U D' R U' R' D"],
    ['Gd-perm', "R U R' U' D R2 U' R U' R' U R' U R2 D'"],
    ['Na-perm', "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'"],
    ['Nb-perm', "R' U R U' R' F' U' F R U R' F R' F' R U' R"],
    ['V-perm', "R' U R' U' y R' F' R2 U' R' U R' F R F y'"],
    ['E-perm', "x' L' U L D' L' U' L D L' U' L D' L' U L D x"],
    // corner-only workhorses (also used by Roux CMLL)
    ['CMLL-a', "R U R' F' R U R' U' R' F R2 U' R'"],
    ['CMLL-b', "F R U' R' U' R U R' F'"],
    ['CMLL-c', "R U2 R' U' R U R' U' R U' R'"],
    ['CMLL-d', "R U2 R2 F R F' R U2 R'"],
    ['CMLL-e', "F R U R' U' R U R' U' F'"],
    ['CMLL-f', "R' U' R U' R' U2 R"],
    ['CMLL-g', "R U R' U R U2 R2 F R F' R U2 R'"],
    // more full-OLL shapes: any that fail verification are simply dropped
    ['OLL-1', "R U2 R2 F R F' U2 R' F R F'"],
    ['OLL-2', "r U r' U2 r U2 R' U2 R U' r'"],
    ['OLL-3', "r' R2 U R' U r U2 r' U M'"],
    ['OLL-4', "M U' r U2 r' U' R U' R' M'"],
    ['OLL-5', "l' U2 L U L' U l"],
    ['OLL-8', "l' U' L U' L' U2 l"],
    ['OLL-9', "R U R' U' R' F R2 U R' U' F'"],
    ['OLL-10', "R U R' U R' F R F' R U2 R'"],
    ['OLL-11', "r U R' U R' F R F' R U2 r'"],
    ['OLL-12', "M' R' U' R U' R' U2 R U' M"],
    ['OLL-13', "F U R U' R2 F' R U R U' R'"],
    ['OLL-14', "R' F R U R' F' R F U' F'"],
    ['OLL-15', "l' U' l L' U' L U l' U l"],
    ['OLL-16', "r U r' R U R' U' r U' r'"],
    ['OLL-17', "R U R' U R' F R F' U2 R' F R F'"],
    ['OLL-19', "r' R U R U R' U' M' R' F R F'"],
    ['OLL-20', "r U R' U' M2 U R U' R' M'"],
    ['OLL-25', "F' r U R' U' r' F R"],
    ['OLL-28', "r U R' U' r' R U R U' R'"],
    ['OLL-29', "r2 D' r U r' D r2 U' r' U' r"],
    ['OLL-30', "r' D' r U' r' D r2 U' r' U r U r'"],
    ['OLL-31', "R' U' F U R U' R' F' R"],
    ['OLL-32', "L U F' U' L' U L F L'"],
    ['OLL-34', "R U R2 U' R' F R U R U' F'"],
    ['OLL-36', "L' U' L U' L' U L U L F' L' F"],
    ['OLL-37', "F R' F' R U R U' R'"],
    ['OLL-38', "R U R' U R U' R' U' R' F R F'"],
    ['OLL-39', "L F' L' U' L U F U' L'"],
    ['OLL-40', "R' F R U R' U' F' U R"],
    ['OLL-41', "R U R' U R U2 R' F R U R' U' F'"],
    ['OLL-42', "R' U' R U' R' U2 R F R U R' U' F'"],
    ['OLL-43', "F' U' L' U L F"],
    ['OLL-46', "R' U' R' F R F' U R"],
    ['OLL-47', "R' U' R' F R F' R' F R F' U R"],
    ['OLL-49', "r U' r2 U r2 U r2 U' r"],
    ['OLL-50', "r' U r2 U' r2 U' r2 U r'"],
    ['OLL-51', "f R U R' U' R U R' U' f'"],
    ['OLL-52', "R U R' U R U' B U' B' R'"],
    ['OLL-53', "l' U2 L U L' U' L U L' U l"],
    ['OLL-54', "r U2 R' U' R U R' U' R U' r'"],
    ['OLL-55', "R U2 R2 U' R U' R' U2 F R F'"],
    ['OLL-56', "r U r' U R U' R' U R U' R' r U' r'"],
    ['OLL-57', "R U R' U' M' U R U' r'"],
];
